url: https://vasugangrade.github.io
# url: https://www.yashgangrade09.com
# baseurl: /agency-jekyll-theme/
# Site settings
title: Vasu Gangrade
email: gangrade.vasu@gmail.com
description: "Hi, I am Yash Gangrade. I am currently a Master of Science Scholar in School of Computing at the University of Utah.
In past, I have worked at Symantec Corporation, Samsung Research Institute and Parliament of India as Software Engineering Intern. I am actively looking for Full Time jobs in Software Engineering and Development starting from May 2019."

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

groups:
- name: Pittsburgh Coal Mining Institute for America
  pic: pcmia
  position: Board of Director
  social:
    - title: facebook
      url: https://www.facebook.com/groups/ariesiitr/
    - title: globe
      url: http://miningorganizations.org/

- name: Society of Mining, Metallurgy & Exploration
  pic: sme
  position: Executive Secretary, Young Leaders Committee
  social:
    - title: facebook
      url: https://www.facebook.com/groups/ariesiitr/
    - title: globe
      url: http://ariesiitr.com/

- name: Emerging Leaders Alliance
  pic: emerging
  position: Recognized Young Leader
  social:
    - title: facebook
      url: https://www.facebook.com/groups/141305179222449/
    - title: globe
      url: http://www.ieeeiitr.com/

honors:
- name: Young Leader Award
  pic: aries
  position: Emerging Leaders Alliance
  social:
    - title: facebook
      url: https://www.facebook.com/groups/ariesiitr/
    - title: globe
      url: http://ariesiitr.com/

- name: Excellence in Government Award (EEO Diversity & Inclusion)
  pic: aries
  position: Pittsburgh Federal Executive Board, CDC
  social:
    - title: facebook
      url: https://www.facebook.com/groups/ariesiitr/
    - title: globe
      url: http://ariesiitr.com/

- name: Design Award
  pic: aries
  position: Government of India
  social:
    - title: facebook
      url: https://www.facebook.com/groups/ariesiitr/
    - title: globe
      url: http://ariesiitr.com/
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/vgangrade/
  - title: facebook
    url: https://www.facebook.com/vasugangrade
  - title: file-pdf-o
    url: https://drive.google.com/open?id=1iyqsnmXTnhLwJUJuq8NlYqH6b34JzVpi
  - title: envelope
    url: mailto:gangrade.vasu@gmail.com
  - title: github
    url: https://github.com/niosh-mining

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
